[package]
name = "uzi-screen"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
rayon.workspace = true
regex.workspace = true
serde_json.workspace = true
uzi-core = { path = "../uzi-core" }
uzi-data = { path = "../uzi-data" }
uzi-report = { path = "../uzi-report" }

[dev-dependencies]
regex.workspace = true
