//! Differential test for the `investor_knowledge` layer.
//!
//! `tests/fixtures/knowledge_cases.json` (generated by
//! `tools/gen_fixtures.py knowledge`) records upstream `market_match`,
//! `check_known_holdings` and `compute_affinity` results over keyword-heavy
//! industry/name/ticker combinations. Together with the panel differential this
//! pins the Layer-1 reality check that drives skip decisions and score bonuses.

use serde_json::Value;

const CASES: &str = include_str!("fixtures/knowledge_cases.json");

#[test]
fn market_scope_holdings_and_affinity_match_upstream() {
    let doc: Value = serde_json::from_str(CASES).expect("knowledge fixture parses");
    let mut bad: Vec<String> = Vec::new();

    for row in doc["markets"].as_array().unwrap() {
        let (id, mkt, want) = (
            row[0].as_str().unwrap(),
            row[1].as_str().unwrap(),
            row[2].as_bool().unwrap(),
        );
        let got = uzi_investors::knowledge::market_match(id, mkt);
        if got != want {
            bad.push(format!("market_match({id}, {mkt:?}) → {got} want {want}"));
        }
    }

    for row in doc["affinity"].as_array().unwrap() {
        let id = row[0].as_str().unwrap();
        let ind = row[1].as_str().unwrap();
        let nm = row[2].as_str().unwrap();
        let want = row[3].as_i64().unwrap();
        let got = uzi_investors::knowledge::compute_affinity(id, ind, nm);
        if got != want {
            bad.push(format!("compute_affinity({id}, {ind:?}, {nm:?}) → {got} want {want}"));
        }
    }

    for row in doc["holdings"].as_array().unwrap() {
        let id = row[0].as_str().unwrap();
        let ticker = row[1].as_str().unwrap();
        let name = row[2].as_str().unwrap();
        let want = row[3].as_array().map(|a| {
            (
                a[0].as_str().unwrap().to_string(),
                a[1].as_str().unwrap().to_string(),
            )
        });
        let got = uzi_investors::knowledge::check_known_holdings(id, ticker, name);
        if got != want {
            bad.push(format!(
                "check_known_holdings({id}, {ticker:?}, {name:?}) → {got:?} want {want:?}"
            ));
        }
    }

    assert!(bad.is_empty(), "{} mismatches:\n{}", bad.len(), bad.join("\n"));
}
