//! Per-rule differential probes.
//!
//! `tests/fixtures/rule_probes.json` is generated by searching a deterministic
//! pseudo-random feature corpus against the upstream lambdas
//! (`tools/gen_fixtures.py probes`): for every `(investor, rule)` it records one feature
//! dict where the Python `check` returns True, one where it returns False and one
//! where it raises (the evaluator then skips the rule). Every probe is trimmed to
//! the feature keys that rule reads, so an exact match here pins the ported check
//! logic rule by rule — including the low-weight rules the two golden panel
//! fixtures never exercise.

use serde_json::Value;

const PROBES: &str = include_str!("fixtures/rule_probes.json");

#[test]
fn every_rule_check_matches_the_upstream_probe() {
    let probes: Value = serde_json::from_str(PROBES).expect("probe fixture parses");
    let mut mismatches: Vec<String> = Vec::new();
    let mut counts = (0usize, 0usize, 0usize); // pass, fail, raise

    for inv in uzi_investors::investors() {
        let id = inv["id"].as_str().unwrap();
        let entry = probes
            .get(id)
            .unwrap_or_else(|| panic!("no probes for {id}"))
            .as_object()
            .unwrap();
        let rules = uzi_investors::criteria::rules_for(id).expect("rules");

        assert_eq!(
            entry.len(),
            rules.len(),
            "{id}: probe count {} != rule count {}",
            entry.len(),
            rules.len()
        );

        for rule in rules {
            let probe = entry
                .get(&rule.rule_id)
                .unwrap_or_else(|| panic!("{id}: no probe for {}", rule.rule_id))
                .as_object()
                .unwrap();
            for (kind, expected) in [
                ("pass", Some(true)),
                ("fail", Some(false)),
                ("raise", None),
            ] {
                let Some(features) = probe.get(kind) else {
                    continue;
                };
                let got = uzi_investors::criteria::safe_check(rule, features);
                match kind {
                    "pass" => counts.0 += 1,
                    "fail" => counts.1 += 1,
                    _ => counts.2 += 1,
                }
                if got != expected {
                    mismatches.push(format!(
                        "{id}/{} {kind}: got {got:?} want {expected:?} — features {features}",
                        rule.rule_id
                    ));
                }
            }
        }
    }

    assert!(
        mismatches.is_empty(),
        "{} rule-probe mismatches:\n{}",
        mismatches.len(),
        mismatches.join("\n")
    );
    // 242 rules; the two constant `lambda f: True` rules (munger/simple_business,
    // lynch/understandable) have no fail probe, everything else has all three.
    assert_eq!(counts.0, 242, "pass probes");
    assert_eq!(counts.1, 240, "fail probes");
    assert!(counts.2 > 190, "raise probes: {}", counts.2);
}

/// The fixture must cover the whole table, and the trimmed probes must stay
/// faithful: re-running the check with the *untrimmed* corpus is not possible
/// here, but the pass/fail/raise triples above are the upstream outcomes.
#[test]
fn probe_fixture_covers_every_rule() {
    let probes: Value = serde_json::from_str(PROBES).expect("probe fixture parses");
    let mut total = 0;
    let mut always_true: Vec<String> = Vec::new();
    for inv in uzi_investors::investors() {
        let id = inv["id"].as_str().unwrap();
        let entry = probes[id].as_object().unwrap();
        for (rule_id, probe) in entry {
            total += 1;
            assert!(probe.get("pass").is_some(), "{id}/{rule_id} has no pass probe");
            if probe.get("fail").is_none() {
                always_true.push(format!("{id}/{rule_id}"));
            }
        }
    }
    assert_eq!(total, 242);
    assert_eq!(
        always_true,
        vec!["munger/simple_business", "lynch/understandable"],
        "only the constant-True rules may lack a fail probe"
    );
}
