//! Differential test for `seat_db.is_in_range`.
//!
//! `tests/fixtures/seat_range.json` is generated by `tools/gen_fixtures.py seats`: for
//! every 游资 (plus an unknown nickname) it records upstream `is_in_range`
//! results across market caps and `fit_rules` flags. The table decides the F 组
//! "out of range → skip" behaviour, including the v2.13.3 implicit 500 亿 cap and
//! the 章盟主 mega-cap allowlist.

use serde_json::{Map, Value};

const SEAT_RANGE: &str = include_str!("fixtures/seat_range.json");

#[test]
fn is_in_range_matches_upstream_for_every_case() {
    let doc: Value = serde_json::from_str(SEAT_RANGE).expect("seat fixture parses");
    let caps = doc["caps"].as_array().unwrap();
    let flags = doc["flags"].as_array().unwrap();
    let cases = doc["cases"].as_array().unwrap();
    assert!(cases.len() > 2000);

    let mut mismatches: Vec<String> = Vec::new();
    for c in cases {
        let nickname = c[0].as_str().unwrap();
        let cap = &caps[c[1].as_u64().unwrap() as usize];
        let flag = &flags[c[2].as_u64().unwrap() as usize];
        let expect = c[3].as_bool().unwrap();

        let mut features: Map<String, Value> = flag.as_object().cloned().unwrap_or_default();
        if let Some(cap) = cap.as_f64() {
            features.insert("market_cap".into(), Value::from(cap));
        }
        let got = uzi_investors::seat_db::is_in_range(nickname, &Value::Object(features.clone()));
        if got != expect {
            mismatches.push(format!(
                "{nickname} {} → got {got} want {expect}",
                Value::Object(features.clone())
            ));
        }
    }
    assert!(
        mismatches.is_empty(),
        "{} is_in_range mismatches:\n{}",
        mismatches.len(),
        mismatches.join("\n")
    );
}
